modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="pcl"
version="4.0.0"
displayName="Clips"
credits="Coded by ExecuteIf"
displayURL="https://github.com/ChengT-cmd/mod_pcl"
logoFile="logo.png"
authors="ExecuteIf"
description='''
More Clips!(Only for PCL users)
'''

[[dependencies.pcl]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




